INSERT INTO T_USER(USER_LOGIN, USER_PASSWORD, USER_NAME, USER_EMAIL) VALUES('rodrigo.kumabe', '$2a$10$QKrVSXaeIK7U6FKsB5GKjORnvW4sYk4PMBsCe2cAeYnrY8MpeN./C', 'Rodrigo Kumabe', 'rodrigo.kumabe@gmail.com');

INSERT INTO T_ROLE(ROLE_NAME) VALUES('ROLE_ADMINISTRATOR');
INSERT INTO T_ROLE(ROLE_NAME) VALUES('ROLE_USER');
INSERT INTO T_ROLE(ROLE_NAME) VALUES('ROLE_ACTUATOR');

INSERT INTO T_USER_X_ROLE(USER_LOGIN, ROLE_NAME) VALUES('rodrigo.kumabe', 'ROLE_ADMINISTRATOR');
INSERT INTO T_USER_X_ROLE(USER_LOGIN, ROLE_NAME) VALUES('rodrigo.kumabe', 'ROLE_USER');
INSERT INTO T_USER_X_ROLE(USER_LOGIN, ROLE_NAME) VALUES('rodrigo.kumabe', 'ROLE_ACTUATOR');
